
name: Allure report
on:
  workflow_dispatch:
  
jobs:
  build-push-deploy:
    name : Pytest
    runs-on : ubuntu-latest
    
    env:
      POETRY_VIRTUALENVS_IN_PROJECT: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          
      - run: pip install poetry~=1.4.0
      - name: cache venv
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - run: poetry install
      
      - name: Install packages
             python -m build allure-python-commons &&
             python -m build allure-python-commons-test &&
             pip install allure-python-commons*/dist/allure-python-commons*.tar.gz
      
      - name: Run tests on all env
        continue-on-error: true
        run: |
          poetry run pytest -v -s -m hello --alluredir=./allure-report/
          
      - name : allure report
        continue-on-error: true
        run: |
         poetry allure serve allure-report
          
  
