
name: Allure report Test
on:
  workflow_dispatch:
  
jobs:
  build-push-deploy:
    name : Pytest
    runs-on : ubuntu-latest
    
    env:
      POETRY_VIRTUALENVS_IN_PROJECT: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          
      - run: pip install poetry~=1.4.0
      - name: cache venv
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - run: poetry install
      
      - name: Run tests on all env
        continue-on-error: true
        run: |
          poetry run pytest -v -s -m hello --alluredir=${{ github.repository }}/gh-pages/allure-report/
          echo ${{ github.repository }}
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git fetch
          git checkout gh-pages
          git add allure-report/
          git commit -m "uodate me"
          cd ${{ github.repository }}/gh-pages/allure-report/
          ls
          
      - name: Install packages
        run : |
             cd allure-results
             ls
             

          
  
