
name: Allure report Test
on:
  workflow_dispatch:
  
jobs:
  build-push-deploy:
    name : Pytest
    runs-on : ubuntu-latest
    
    env:
      POETRY_VIRTUALENVS_IN_PROJECT: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          
      - run: pip install poetry~=1.4.0
      - name: cache venv
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - run: poetry install
      
      - name: Run tests on all env
        continue-on-error: true
        env:
          SRC_FOLDER_PATH: 'allure-report'
          TARGET_BRANCH: 'gh-pages'
        run: |
          poetry run pytest -v -s -m hello --alluredir=./allure-report/
          echo ${{ github.repository }}
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          
          git fetch                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch
          cd allure-report
          ls
          
      - name: Install packages
        run : |
             cd allure-results
             ls
             

          
  
