name: Branch Name
on:
  workflow_dispatch:
  
jobs:
  build-push-deploy:
    name : Pytest
    runs-on : macos-latest
    
    steps:
      - run: |
          run: echo "${GITHUB_REF})"
          id: extract_branch 
