name: Branch Name
on:
  workflow_dispatch:
  
jobs:
  build-push-deploy:
    name : Pytest
    runs-on : macos-latest
    
    steps:
      - run: |
          echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"
          id: extract_branch
      - run : echo ${{ steps.extract_branch.outputs.branch }}    
