name: Branch Name
on:
  workflow_dispatch:
  
jobs:
  build-push-deploy:
    name : Branch name
    runs-on : macos-latest
    
    steps:
      
      - name : get the branch name
        id: extract_branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"

      - name : name of branch
        run : echo ${{ steps.extract_branch.outputs.branch }}    
