on:
  schedule:
    - cron: '1 * * * *'
jobs:
    printme:
      runs-on: ubuntu-latest
      steps:
        - run : echo "Hello World from ubuntu one"
    scanme:
      runs-on : ubuntu-latest
      steps:
        - run : echo "Hello World from ubuntu two"
    
  
