on:
 push:
  branches:
   - main
   
jobs:
 print_hello:
  runs-on: ubuntu-latest
  steps:
   - run: echo "Hello World From GITHUB ACTIONS Cron"
 print_world:
  runs-on : windows-latest
  steps:
   - run: java --version
  

