on:
 pull_request:
  branches:
   - main
   
jobs:
 print_hello:
  runs-on: ubuntu-latest
  steps:
   - run: echo "Hello World From GITHUB ACTIONS Cron"
 print_world:
  runs-on : windows-latest
  steps:
   - run: |
      touch tf/rqttkfbucket
      java -version
