name: issue commit

on:
  issues:
    types:
      [opened]
jobs:
  github_comment:
    runs-on: ubuntu-latest
    steps:
      - name: using community api
        run : echo '${{toJSON(github.event)}}'
        shell : bash
