name: issue commit

on:
  issues:
    types:
      [opened]
jobs:
  github_comment:
    runs-on: ubuntu-latest
    steps:
      - name: using community api
        run : echo '${{toJSON(github.event)}}'
        shell : bash
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{(github.event.number)}}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: heart
