on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run : echo "job 1 is executed"
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job 2 is executed"
  jobs3:
    needs: job2
    runs-on: ubuntu-latest
    steps:
    - run: echo "job 3 is executed"
      
