on:
  schedule:
    - cron : '*/1 * * * *'
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run : echo "job 1 is executed"
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job 2 is executed"
