on:
  push:
    branches:
      - main
jobs:
  multipleEnv_test:
    strategy:
      matrix:
        versions: [11, latest]
    runs-on : ubuntu-${{matrix.version}}
    steps :
      - run : echo "i am running on "${{matrix.version}}
