name: Random Test
on:
 workflow_dispatch:
 
jobs:
  multipleEnv_test:
    strategy:
      matrix:
        version: [11, latest]
    runs-on : ubuntu-${{ matrix.version }}
    env:
      RANDOM_STR : $(date +%s)
    steps :
      - run : |
          echo "i am running on "${{ matrix.version }}
          echo $RANDOM_STR
        
      
