on:
  push:
    branches:
      - main
jobs:
  multipleEnv_test:
    strategy:
      matrix:
        versions: [11, latest]
  steps:
    runs-on : ubuntu-{{matrix.version}}
    run : echo "i am running on "{{matrix.version}}
