on:
  workflow_dispatch:
    inputs:
      env:
        description : "Enter pip install"
        default: "python -v"
jobs:
  inputtype:
    runs-on: ubuntu-latest
    steps: 
     - run: |
         ${{ github.event.inputs.env }}
         python -verison
         pytest
