on:
  workflow_dispatch:
    inputs:
      env:
        description : "Enter pip install"
        default: "python3 --version"
jobs:
  inputtype:
    runs-on: ubuntu-latest
    steps: 
     - run: |
         ${{ github.event.inputs.env }}
         python3 --version
         pytest
