
name: PIP Allure report Test
on:
  workflow_dispatch:
  
jobs:
  build-push-deploy:
    name : Pytest
    runs-on : macos-latest
    
    steps:
      - run: |
          brew install allure
          allure --version
          
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          
      - run: |
            pip3 install pytest
            pip3 install pytest-allure

     
  
