
name: PIP Allure report Test
on:
  workflow_dispatch:
  
jobs:
  build-push-deploy:
    name : Pytest
    runs-on : macos-latest
    
    steps:
      - run: |
          brew install allure
          allure --version
          
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          
      - run: |
            pip3 install pytest
            pip3 install allure-pytest
    
      - name: Run tests on all env
        continue-on-error: true
        run: |
            git checkout -B gh-pages
            pytest -v -s -m hello --alluredir=./allure-report/${{ github.run_id }}/
            allure generate ./allure-report/${{ github.run_id }} -c -o ./allure-results/${{ github.run_id }}
            echo ${{ github.repository }}
            git config --global user.email "no-reply@github.com"
            git config --global user.name "GitHub Actions"
            git add .
            git commit -m "update me"
            git push origin gh-pages
            git fetch
            git checkout main
            git push origin --delete gh_pages

     
  
