
name: PIP Allure report Test
on:
  workflow_dispatch:
  
jobs:
  build-push-deploy:
    name : Pytest
    runs-on : ubuntu-latest
    
    steps:
      - run: |
         sudo apt-add-repository ppa:qameta/allure
         sudo apt-get update 
         sudo apt-get install allure
         allure --version
          
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          
      - run: |
            pip3 install pytest
            pip3 install allure-pytest
            
      - name : checkout the branch
        continue-on-error : true
        run: |
            git checkout -B gh-pages
    
      - name: Run tests on all env create order
        continue-on-error: true
        run: |
            pytest -v -s -m hello --alluredir=./allure-report/${{ github.run_number }}/
            
      - name: Run tests on all env inventory adjustment
        continue-on-error: true
        run: |
            pytest -v -s -m order --alluredir=./allure-report/${{ github.run_number }}/
  
      - name : get branch name
        id : branch_name
        run: |
          git fetch
          echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"
          
      - name : Branch Name
        run : echo ${{ steps.branch_name.outputs.branch }}              

      - name : Commit the changes
        continue-on-error: true
        run : |
            allure generate ./allure-report/${{ github.run_number }} -c -o ./allure-results/${{ github.run_number }}   
            echo ${{ github.repository }}
            git config --global user.email "no-reply@github.com"
            git config --global user.name "GitHub Actions"
            echo '<!DOCTYPE html><html dir="ltr"><head><meta charset="utf-8"><title>Allure Report</title><link rel="favicon" href="favicon.ico?v=2"><link rel="stylesheet" type="text/css" href="styles.css"><link rel="stylesheet" href="plugins/screen-diff/styles.css"></head><body><div id="alert"></div><div id="content"><span class="spinner"><span class="spinner__circle"></span></span></div><div id="popup"></div><script src="app.js"></script><script src="plugins/behaviors/index.js"></script><script src="plugins/packages/index.js"></script><script src="plugins/screen-diff/index.js"></script></body></html>' > ./allure-results/${{ github.run_number }}/index2.html
            git add .
            git commit -m "${{github.run_number}} allure-report"
            git push origin gh-pages
            git fetch
            git checkout main
            
            

  
