
name: PIP Allure report Test
on:
  workflow_dispatch:
  
jobs:
  build-push-deploy:
    name : Pytest
    runs-on : ubuntu-latest
    
    steps:
      - run: |
          curl -o allure-2.7.0.zip -Ls https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.7.0/allure-2.7.0.zip
          sudo tar -zxvf allure-2.7.0.zip -C /opt/
          sudo ln -s /opt/allure-2.7.0/bin/allure /usr/bin/allure
          rm -rf allure-2.7.0.zip
          allure --version
          
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          
      - run: |
            pip3 install pytest
            pip3 install pytest-allure

     
  
