name: Build and Push RQ Service to Google Cloud Run
on:
  workflow_dispatch:
    inputs :
      region:
        description: 'region to deploy'
        required: true
        default: 'us-east1'
jobs:
  build-push-deploy:
    name : Build the docker image
    runs-on : ubuntu-latest
    permissions:
      id-token: write
      contents : read
    env:
      IMAGE_NAME: rqservice
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - name : checkout
        uses : actions/checkout@v2

      - name : Authenticate to Google Cloud
        uses : google-github-actions/auth@v0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name : Build Docker Image
        run : docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA .

      - name : Configure Docker Client
        run :  gcloud auth configure-docker --quite

      - name : Push Docker Image to Google Cloud Run (GCR)
        run : docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA
