name: GCP Build and Push RQ Service to Google Cloud Run
on:
  workflow_dispatch:
    inputs :
      region:
        description: 'region to deploy'
        required: true
        default: 'us-east1'
jobs:
  build-push-deploy:
    name : Build the docker image
    runs-on : ubuntu-latest
    permissions:
      id-token: write
      contents : read
    env:
      IMAGE_NAME: rqservice
      PROJECT_ID: default-demo-app-e16ba

    steps:
      - name : checkout
        uses : actions/checkout@v3
  
      - name : Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          version : '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: ${{ env.PROJECT_ID }}
      
      - name: Use gcloud CLI
        run:  gcloud info
        
      - name : key
        run : echo ${{ env.GCP_SA_KEY_JSON }}

      - name : Build Docker Image
        run : docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA .

      - name : Configure Docker Client
        run :  gcloud auth configure-docker --quiet
        
      - name : Configure Docker CR
        run :  gcloud auth configure-docker gcr.io

      - name : Push Docker Image to Google Cloud Run (GCR)
        run :  docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA
