on:
  push:
    branches:
      - main
jobs:
  run_go_program:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name : setup my golang
      - uses: actions/setup-go@v2
      - run : go run ./...
