on:
  push:
    branches:
      - main
jobs:
  run_go_program:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name : setup my golang
        uses: actions/setup-go@v2
        with:
         go-version: 1.17
         
      - name : mygoprg
        run : go run ./main.go
        
      - name : setup my python
        uses : actions/setup-python@v4
        
      - name : pyrunprog
        run: ./python hello.py
