name: Terraform Cloud Run
on:
  workflow_dispatch:
    inputs :
      region:
        description: 'region to deploy'
        required: true
        default: 'us-east1'
jobs:
  tf-file-states:
    name : setup-terraform
    runs-on : ubuntu-latest
    defaults:
      run:
       working-directory: tf
    
    permissions:
      id-token: write
      contents : read
    env:
      IMAGE_NAME: rqservice
      PROJECT_ID: default-demo-app-e16ba

    steps:
      - name : checkout
        uses : actions/checkout@v3
      
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
         terraform_version: 1.3.0

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init    
